# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: text_pipeline.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'text_pipeline.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13text_pipeline.proto\x12\rtext_pipeline\"\xab\x01\n\x0cPipelineText\x12\x15\n\roriginal_text\x18\x01 \x01(\t\x12\x16\n\x0eprocessed_text\x18\x02 \x01(\t\x12;\n\x08metadata\x18\x03 \x03(\x0b\x32).text_pipeline.PipelineText.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32X\n\tValidator\x12K\n\x0fValidateAndPass\x12\x1b.text_pipeline.PipelineText\x1a\x1b.text_pipeline.PipelineText2V\n\x08Reverser\x12J\n\x0eReverseAndPass\x12\x1b.text_pipeline.PipelineText\x1a\x1b.text_pipeline.PipelineText2[\n\x0bTransformer\x12L\n\x10TransformAndPass\x12\x1b.text_pipeline.PipelineText\x1a\x1b.text_pipeline.PipelineText2V\n\x08\x41nalyzer\x12J\n\x0e\x41nalyzeAndPass\x12\x1b.text_pipeline.PipelineText\x1a\x1b.text_pipeline.PipelineText2U\n\tFormatter\x12H\n\x0c\x46ormatOutput\x12\x1b.text_pipeline.PipelineText\x1a\x1b.text_pipeline.PipelineTextb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'text_pipeline_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PIPELINETEXT_METADATAENTRY']._loaded_options = None
  _globals['_PIPELINETEXT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_PIPELINETEXT']._serialized_start=39
  _globals['_PIPELINETEXT']._serialized_end=210
  _globals['_PIPELINETEXT_METADATAENTRY']._serialized_start=163
  _globals['_PIPELINETEXT_METADATAENTRY']._serialized_end=210
  _globals['_VALIDATOR']._serialized_start=212
  _globals['_VALIDATOR']._serialized_end=300
  _globals['_REVERSER']._serialized_start=302
  _globals['_REVERSER']._serialized_end=388
  _globals['_TRANSFORMER']._serialized_start=390
  _globals['_TRANSFORMER']._serialized_end=481
  _globals['_ANALYZER']._serialized_start=483
  _globals['_ANALYZER']._serialized_end=569
  _globals['_FORMATTER']._serialized_start=571
  _globals['_FORMATTER']._serialized_end=656
# @@protoc_insertion_point(module_scope)
